---

# Excecoes do Rubycritic
detectors:

  UtilityFunction:
    exclude:
      - "SecretsHelper#get_secrets"
      - "ServicesHTTPartyHelper#load_contract_api"

  NilCheck:
    exclude:
      - "StepsHelper"

  Attribute:
    exclude:
      - /([\w.]+)Endpoint/
